cars:
  0:
    name: "Jeep Wrangler"
    health: 100.0
    max_speed: 2.5
    acceleration: 0.5
    angular_speed: 1.5
    mass: 50.0  
  1:
    name: "Ferrari F40"
    health: 50.0
    max_speed: 3.5
    acceleration: 1.2
    angular_speed: 2.0
    mass: 25.0  
  2:
    name: "BMW Z4"
    health: 90.0
    max_speed: 3.0
    acceleration: 1.0
    angular_speed: 1.7
    mass: 45.0  
  3:
    name: "VW Beetle"
    health: 75.0
    max_speed: 2.5
    acceleration: 1.0
    angular_speed: 2.0
    mass: 37.5  
  4:
    name: "Ford Bronco"
    health: 200.0
    max_speed: 2.0
    acceleration: 0.3
    angular_speed: 1.5
    mass: 100.0  
  5:
    name: "Ford F100"
    health: 150.0
    max_speed: 2.25
    acceleration: 0.4
    angular_speed: 1.5
    mass: 75.0  
  6:
    name: "MB S-Class"
    health: 125.0
    max_speed: 2.3
    acceleration: 0.5
    angular_speed: 1.5
    mass: 62.5  

game_phases_timers:
  countdown: 10     # Seconds. First 7 -> "Ready", last 3 -> "3", "2", "1", "Go!"
  racing: 10        # Minutes. Time for the race
  showing_stats: 10 # Seconds. Time to show race results
  modifying_car: 10 # Seconds. Time to modify car between races
  game_end: 15      # Seconds. Time to show final results

number_of_races: 4

rate_loop: 60
