#ifndef MODIF_CONSTANTS
#define MODIF_CONSTANTS

#define PENALTY_PER_IMPROVEMENT 5

#define VELOCITY_IMPROVEMENT_PERCENTAGE 1.5f
#define HEALTH_IMPROVEMENT_PERCENTAGE 1.05f
#define ACCELERATION_IMPROVEMENT_PERCENTAGE 1.1f
#define MASS_IMPROVEMENT_PERCENTAGE 1.1f

#endif  // MODIF_CONSTANTS
